import assert from 'node:assert/strict';
import { bookingTotals, bookingItems, confirmAssistantBooking } from '../src/lib/assistantBooking';
import type { BookingInput, BookingResult } from '../src/lib/bookingServerFn';
import type { CartItem } from '../src/data/bookingCatalogue';
const item = { service: { id: 'auto', label: 'Auto' }, formule: { id: 'argent', name: 'Argent', price: 99, durationMin: 90, options: [{ id: 'acariens', name: 'Vapeur', price: 19 }] }, options: ['acariens'] } as CartItem;
assert.deepEqual(bookingTotals([item]), { price: 118, duration: 90 });
assert.deepEqual(bookingTotals([item, item]), { price: 236, duration: 180 });
assert.equal(bookingItems([item])[0]?.options[0]?.name, 'Vapeur');
assert.equal(bookingItems([{ ...item, options: ['unknown'] }])[0]?.options.length, 0);
const data = { items: bookingItems([item]), total_price: 118, duration_min: 90, booking_date: '2030-01-02', booking_time: '10:00', client_name: 'Test', client_email: 'test@example.com', client_phone: '0600000000', client_street: 'Rue test', client_zip: '31000', client_city: 'Toulouse', cancel_token: 'pending', gcal_event_id: 'abcde' } satisfies BookingInput;
let creates = 0, emails = 0;
let response: BookingResult = { success: true, gcal_event_id: 'abcde', cancel_token: 'signed' };
const deps = { create: async () => { creates++; return response; }, email: async () => { emails++; } };
await assert.rejects(confirmAssistantBooking(false, data, deps), /CONFIRMATION_REQUIRED/);
assert.equal(creates, 0); assert.equal(emails, 0);
response = { success: false, gcal_event_id: null, cancel_token: 'pending', error: 'SLOT_TAKEN' };
assert.equal((await confirmAssistantBooking(true, data, deps)).error, 'SLOT_TAKEN');
assert.equal(emails, 0);
response = { success: false, gcal_event_id: null, cancel_token: 'pending', error: 'BOOKING_FAILED' };
assert.equal((await confirmAssistantBooking(true, data, deps)).success, false);
assert.equal(emails, 0);
response = { success: true, gcal_event_id: 'abcde', cancel_token: 'signed' };
const ok = await confirmAssistantBooking(true, data, deps);
assert.equal(ok.success, true); assert.equal(ok.emailSent, true); assert.equal(emails, 1);
const emailFail = await confirmAssistantBooking(true, data, { ...deps, email: async () => { throw new Error('SMTP'); } });
assert.equal(emailFail.success, true); assert.equal(emailFail.emailSent, false);
assert.equal(creates, 4);
console.log('7 checks passed: totals, unchanged duration, catalogue mapping, explicit confirmation, slot conflict, calendar failure, email failure without duplicate booking.');
