import assert from 'node:assert/strict';
import { euroCents, reservationAmounts } from '../src/lib/reservationSummary';
import { answerCustomer, shouldStartBooking } from '../src/lib/chatAssistant';
assert.equal(euroCents('1 250,50 €'),125050);
assert.equal(euroCents('-10'),null);
assert.equal(euroCents('100 € à confirmer'),null);
assert.deepEqual(reservationAmounts('💶 TOTAL : 250 €\nAcompte reçu : 125 €'),{total:25000,deposit:12500,balance:12500});
assert.deepEqual(reservationAmounts('Devis : 250 €\nAcompte demandé : 125 €'),{total:null,deposit:null,balance:null});
assert.deepEqual(reservationAmounts('TOTAL : 99 €',{cfPaymentAtEnd:'true'}),{total:9900,deposit:0,balance:9900});
assert.equal(reservationAmounts('TOTAL : 99 €',{},'100').balance,null);
assert.equal(reservationAmounts('TOTAL : 99 €',{},'49.50').balance,4950);
assert.equal(shouldStartBooking('Je veux réserver une toiture'),false);
assert.equal(shouldStartBooking('Je veux réserver mon canapé'),true);
assert.equal(shouldStartBooking('réserver un devis pour mon canapé'),false);
assert.equal(shouldStartBooking('quelles disponibilités ?', '/nettoyage-diogene-toulouse'),false);
assert.equal(shouldStartBooking('annuler ma réservation'),false);
assert.match(answerCustomer('réserver pour Diogène').text,/50 %/);
assert.match(answerCustomer('canapé cuir').service!,/cuir/);
assert.match(answerCustomer('réserver des vitres').text,/50 %/);
assert.match(answerCustomer('disponibilités fin de chantier').text,/50 %/);
console.log('17 checks passed: exact amounts, no inferred payment, quote routing, cancellation and leather context.');
